USE [JAI_DAILY_EXPORT]
GO
SET IDENTITY_INSERT [dbo].[Export_PrintJob] ON 
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (4, N'PRINT_4.1', N'RedemptionLetter_OCPB61_B PRINT_4.1', N'dbo.SP_Export_Print_4_1', N'RedemptionLetter_OCPB61_B_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-08-25T04:19:10.4971675' AS DateTime2), CAST(N'2025-08-25T04:19:10.4971675' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (6, N'PRINT_4.2', N'RedemptionLetter_OCPB65_B PRINT_4.2', N'dbo.SP_Export_Print_4_2', N'RedemptionLetter_OCPB65_B_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-08-25T04:32:09.7776181' AS DateTime2), CAST(N'2025-08-25T04:32:09.7776181' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (7, N'PRINT_4.3', N'RedemptionLetter_CRL _B PRINT_4.3', N'dbo.SP_Export_Print_4_3', N'RedemptionLetter_CRL_B_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-08-25T04:32:23.9265393' AS DateTime2), CAST(N'2025-08-25T04:32:23.9265393' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (8, N'PRINT_4.4', N'AuctionLetter_R2_C2C_B PRINT_4.4', N'dbo.SP_Export_Print_4_4', N'AuctionLetter_R2_C2C_B_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-08-25T04:32:35.6631283' AS DateTime2), CAST(N'2025-08-25T04:32:35.6631283' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (21, N'PRINT_4.1.1', N'RedemptionLetter_OCPB61_NoG PRINT_4.1.1', N'dbo.SP_Export_Print_4_1_1', N'RedemptionLetter_OCPB61_NoG_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T03:34:40.1389844' AS DateTime2), CAST(N'2025-10-16T03:34:40.1389844' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (22, N'PRINT_4.2.1', N'RedemptionLetter_OCPB65_NoG PRINT_4.2.1', N'dbo.SP_Export_Print_4_2_1', N'RedemptionLetter_OCPB65_NoG_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T04:43:03.4306822' AS DateTime2), CAST(N'2025-10-16T04:43:03.4306822' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (25, N'PRINT_4.3.1', N'RedemptionLetter_CRL _NoG PRINT_4.3.1', N'dbo.SP_Export_Print_4_3_1', N'RedemptionLetter_CRL_NoG_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T05:07:32.8726152' AS DateTime2), CAST(N'2025-10-16T05:07:32.8726152' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (28, N'PRINT_4.4.1', N'AuctionLetter_R2_C2C_NoG PRINT_4.4.1', N'dbo.SP_Export_Print_4_4_1', N'AuctionLetter_R2_C2C_NoG_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T06:44:55.4443894' AS DateTime2), CAST(N'2025-10-16T06:44:55.4443894' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (29, N'PRINT_4.4.2', N'AuctionLetter_R2_CRL_B PRINT_4.4.2', N'dbo.SP_Export_Print_4_4_2', N'AuctionLetter_R2_CRL_B_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T07:55:06.7321712' AS DateTime2), CAST(N'2025-10-16T07:55:06.7321712' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (30, N'PRINT_4.4.3', N'AuctionLetter_R2_CRL_NoG PRINT_4.4.3', N'dbo.SP_Export_Print_4_4_3', N'AuctionLetter_R2_CRL_NoG_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T08:24:52.4336610' AS DateTime2), CAST(N'2025-10-16T08:24:52.4336610' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (31, N'PRINT_18', N'Sale of repo PRINT_18', N'dbo.SP_Export_Print_18', N'LossOnSaleLetter CRL_B_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T09:10:54.3352820' AS DateTime2), CAST(N'2025-10-16T09:10:54.3352820' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (32, N'PRINT_18.1', N'Sale of repo PRINT_18.1', N'dbo.SP_Export_Print_18_1', N'LossOnSaleLetter CRL_NoG_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T09:25:55.6777153' AS DateTime2), CAST(N'2025-10-16T09:25:55.6777153' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (38, N'PRINT_19.1', N'Sale of repo PRINT_19.1', N'dbo.SP_Export_Print_19_1', N'LossOnSaleLetter C2C_B_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T09:29:58.7103298' AS DateTime2), CAST(N'2025-10-16T09:29:58.7103298' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (39, N'PRINT_19.1.1', N'Sale of repo PRINT_19.1.1', N'dbo.SP_Export_Print_19_1_1', N'LossOnSaleLetter C2C_NoG_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T09:31:01.0483608' AS DateTime2), CAST(N'2025-10-16T09:31:01.0483608' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (40, N'PRINT_19.3', N'Sale of repo PRINT_19.3', N'dbo.SP_Export_Print_19_3', N'GainOnSaleLetter_C2C_NoG_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T09:33:04.8466172' AS DateTime2), CAST(N'2025-10-16T09:33:04.8466172' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (41, N'PRINT_19.3.1', N'Sale of repo PRINT_19.3.1', N'dbo.SP_Export_Print_19_3_1', N'GainOnSaleLetter_C2C_B_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T09:34:06.2396727' AS DateTime2), CAST(N'2025-10-16T09:34:06.2396727' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (42, N'PRINT_19.4', N'Sale of repo PRINT_19.4', N'dbo.SP_Export_Print_19_4', N'GainOnSaleLetter_CRL_NoG_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T09:35:07.1607280' AS DateTime2), CAST(N'2025-10-16T09:35:07.1607280' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (43, N'PRINT_19.4.1', N'Sale of repo PRINT_19.4.1', N'dbo.SP_Export_Print_19_4_1', N'GainOnSaleLetter_CRL_B_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T09:36:10.0669029' AS DateTime2), CAST(N'2025-10-16T09:36:10.0669029' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (44, N'PRINT_18g', N'Sale of repo PRINT_18g', N'dbo.SP_Export_Print_18g', N'LossOnSaleLetter CRL_G_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T09:37:42.5399125' AS DateTime2), CAST(N'2025-10-16T09:37:42.5399125' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (45, N'PRINT_19.1g', N'Sale of repo PRINT_19.1g', N'dbo.SP_Export_Print_19_1g', N'LossOnSaleLetter C2C_G_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T09:38:37.4253682' AS DateTime2), CAST(N'2025-10-16T09:38:37.4253682' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (49, N'PRINT_4.1G', N'RedemptionLetter_OCPB61_G PRINT_4.1G', N'dbo.SP_Export_Print_4_1G', N'RedemptionLetter_OCPB61_G_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T10:22:20.2593083' AS DateTime2), CAST(N'2025-10-16T10:22:20.2593083' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (50, N'PRINT_4.2G', N'RedemptionLetter_OCPB65_G PRINT_4.2G', N'dbo.SP_Export_Print_4_2G', N'RedemptionLetter_OCPB65_G_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T10:23:05.7652074' AS DateTime2), CAST(N'2025-10-16T10:23:05.7652074' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (51, N'PRINT_4.3G', N'RedemptionLetter_CRL_G PRINT_4.3G', N'dbo.SP_Export_Print_4_3G', N'RedemptionLetter_CRL_G_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T10:23:59.7327601' AS DateTime2), CAST(N'2025-10-16T10:23:59.7327601' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (52, N'PRINT_4.4G', N'AuctionNotiLetter_R2_C2C_G PRINT_4.4G', N'dbo.SP_Export_Print_4_4G', N'AuctionNotiLetter_R2_C2C_G_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T10:24:48.8858806' AS DateTime2), CAST(N'2025-10-16T10:24:48.8858806' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
INSERT [dbo].[Export_PrintJob] ([JobId], [JobCode], [JobName], [StoredProcName], [FileNameTemplate], [SheetName], [IsActive], [ExecuteOrder], [CreatedAt], [UpdatedAt], [OutputSubfolder], [OutputRootKey], [SourceTableName], [PrimaryKeyColumnName]) VALUES (53, N'PRINT_4.4.2G', N'AuctionNotiLetter_R2_CRL_G PRINT_4.4.2G', N'dbo.SP_Export_Print_4_4_2G', N'AuctionNotiLetter_R2_CRL_G_{DDMMYYYY}', N'Sheet1', 1, 1, CAST(N'2025-10-16T10:25:54.4492352' AS DateTime2), CAST(N'2025-10-16T10:25:54.4492352' AS DateTime2), NULL, N'PRINT_FOLDER', N'jai_redemption_letter_transaction', N'letter_id')
GO
SET IDENTITY_INSERT [dbo].[Export_PrintJob] OFF
GO
INSERT [dbo].[Export_PrintSetting] ([SettingKey], [SettingValue]) VALUES (N'SHAREPOINT_SITE_URL', N'https://ngernhaijai.sharepoint.com/sites/Internal-LMS-NonProd/')
GO
INSERT [dbo].[Export_PrintSetting] ([SettingKey], [SettingValue]) VALUES (N'SHAREPOINT_FOLDER', N'Internal-LMS-NonProd\Documents\UAT\Collection\Adler')
GO
INSERT [dbo].[Export_PrintSetting] ([SettingKey], [SettingValue]) VALUES (N'LOG_FOLDER', N'C:\Data\Exports\Logs')
GO
INSERT [dbo].[Export_PrintSetting] ([SettingKey], [SettingValue]) VALUES (N'PRINT_FOLDER', N'C:\Data\Exports\PRINTING')
GO
INSERT [dbo].[Export_PrintSetting] ([SettingKey], [SettingValue]) VALUES (N'BACKUP_FOLDER', N'C:\Data\Exports\PRINTING\BACKUP')
GO
INSERT [dbo].[Export_PrintSetting] ([SettingKey], [SettingValue]) VALUES (N'SHAREPOINT_TENANT_ID', N'8017f6e0-c369-4ed8-a714-1bc15ed4c283')
GO
INSERT [dbo].[Export_PrintSetting] ([SettingKey], [SettingValue]) VALUES (N'SHAREPOINT_CLIENT_ID', N'ade9bba0-2890-41a4-9ded-df285a886da0')
GO
INSERT [dbo].[Export_PrintSetting] ([SettingKey], [SettingValue]) VALUES (N'SHAREPOINT_CERT_PATH', N'./SharePoint Service - COC - NonProd.pfx')
GO
INSERT [dbo].[Export_PrintSetting] ([SettingKey], [SettingValue]) VALUES (N'SHAREPOINT_CERT_PASS', N'757LKf9s')
GO
INSERT [dbo].[Export_PrintSetting] ([SettingKey], [SettingValue]) VALUES (N'SHAREPOINT_UPLOAD_FOLDER', N'Documents/UAT/Collection/Adler')
GO
